import { StyleRank, StyleRankInfo, Condition } from './types';

export const STYLE_RANKS: StyleRankInfo[] = [
  { rank: StyleRank.D, label: 'D', name: 'Dirty!', bonus: 'Nenhum.' },
  { rank: StyleRank.C, label: 'C', name: 'Cruel!', bonus: '+2 em testes de Ataque e +2 de Defesa.' },
  { rank: StyleRank.B, label: 'B', name: 'Brutal!', bonus: '+1d6 de dano em todos os ataques e rituais.' },
  { rank: StyleRank.A, label: 'A', name: 'Atomic!', bonus: 'Você recebe uma Ação de Movimento extra por turno.' },
  { rank: StyleRank.S, label: 'S', name: 'Smokin\'!', bonus: '+2d6 de dano e margem de crítico aumenta em +1.' },
  { rank: StyleRank.SS, label: 'SS', name: 'Smokin\' Style!', bonus: 'Você recupera 2 PE no início de cada um dos seus turnos.' },
  { rank: StyleRank.SSS, label: 'SSS', name: 'Smokin\' Sexy Style!', bonus: '+5d6 de dano e você pode realizar uma Ação Padrão adicional (uma vez por cena).' },
];

export const INITIAL_CONDITIONS: Condition[] = [
  { id: '1', name: 'Abalado', description: 'O personagem sofre -1d20 em testes. Se ficar abalado novamente, em vez disso fica apavorado. Condição de medo.', summary: '-1d20 em testes' },
  { id: '2', name: 'Agarrado', description: 'O personagem fica desprevenido e imóvel, sofre -1d20 em testes de ataque e só pode atacar com armas leves. Um personagem fazendo um ataque à distância contra um alvo envolvido na manobra agarrar tem 50% de chance de acertar o alvo errado. Condição de paralisia.', summary: 'Desprevenido, Imóvel, -1d20 em ataque', causes: ['11', '23'] },
  { id: '3', name: 'Alquebrado', description: 'O custo em pontos de esforço das habilidades e dos rituais do personagem aumenta em +1. Condição mental.', summary: '+1 Custo PE' },
  { id: '4', name: 'Apavorado', description: 'O personagem sofre -1d20 em testes de perícia e deve fugir da fonte do medo da maneira mais eficiente possível. Se não puder, poderá agir, mas não poderá se aproximar voluntariamente da fonte do medo. Se ficar apavorado novamente, fica em pânico. Condição de medo.', summary: '-1d20 em perícia, Fugir' },
  { id: '5', name: 'Asfixiado', description: 'O personagem não pode respirar. Pode prender o fôlego por rodadas igual ao Vigor. Ao final da última rodada, fica morrendo.', summary: 'Sem fôlego' },
  { id: '6', name: 'Atordoado', description: 'O personagem fica desprevenido e não pode fazer ações. Condição mental.', summary: 'Desprevenido, Sem ações', causes: ['11'] },
  { id: '7', name: 'Caído', description: 'Deitado no chão. O personagem sofre -1d20 em ataques corpo a corpo e seu deslocamento é reduzido a 1,5m. Além disso, sofre -5 na Defesa contra ataques corpo a corpo, mas recebe +5 na Defesa contra ataques à distância.', summary: '-1d20 em ataque, -5 Defesa' },
  { id: '8', name: 'Cego', description: 'O personagem fica desprevenido e lento, não pode fazer testes de Percepção para observar e sofre -1d20 em testes de perícias baseados em Agilidade ou Força. Todos os alvos de seus ataques recebem camuflagem total. Condição de sentidos.', summary: 'Desprevenido, Lento, -1d20 em perícia', causes: ['11', '26'] },
  { id: '9', name: 'Confuso', description: 'O personagem comporta-se de modo aleatório. Role 1d6 no início de seus turnos: 1) Movimenta-se aleatoriamente; 2-3) Não pode fazer ações; 4-5) Ataca o ser mais próximo; 6) Condição termina. Condição mental.', summary: 'Ações aleatórias' },
  { id: '10', name: 'Debilitado', description: 'O personagem sofre -1d20 em testes de Agilidade, Força e Vigor. Se o personagem ficar debilitado novamente, em vez disso fica inconsciente.', summary: '-1d20 em testes' },
  { id: '11', name: 'Desprevenido', description: 'Despreparado para reagir. O personagem sofre -5 na Defesa e -1d20 em Reflexos. Você fica desprevenido contra inimigos que não possa perceber.', summary: '-5 Defesa, -1d20 em reflexos' },
  { id: '12', name: 'Doente', description: 'Sob efeito de uma doença.', summary: 'Doente' },
  { id: '13', name: 'Em chamas', description: 'O personagem está pegando fogo. No início de seus turnos, sofre 1d6 pontos de dano de fogo. O personagem pode gastar uma ação padrão para apagar o fogo com as mãos.', summary: '1d6 Dano Fogo/turno' },
  { id: '14', name: 'Enjoado', description: 'O personagem só pode realizar uma ação padrão ou de movimento (não ambas) por rodada.', summary: 'Apenas 1 Ação Padrão ou Mov.' },
  { id: '15', name: 'Enredado', description: 'O personagem fica lento, vulnerável e sofre -1d20 em testes de ataque. Condição de paralisia.', summary: 'Lento, Vulnerável, -1d20 em ataque', causes: ['26', '36'] },
  { id: '16', name: 'Envenenado', description: 'Efeito varia de acordo com o veneno. Pode ser outra condição ou dano recorrente.', summary: 'Efeito veneno' },
  { id: '17', name: 'Esmorecido', description: 'O personagem sofre -2d20 em testes de Intelecto e Presença. Se ficar esmorecido novamente, em vez disso fica desesperado. Condição mental.', summary: '-2d20 em testes' },
  { id: '18', name: 'Exausto', description: 'O personagem fica debilitado, lento e vulnerável. Se ficar exausto novamente, em vez disso fica inconsciente. Condição de fadiga.', summary: 'Debilitado, Lento, Vulnerável', causes: ['10', '26', '36'] },
  { id: '19', name: 'Fascinado', description: 'Atenção presa em algo. Sofre -2d20 em Percepção e não pode fazer ações, exceto observar aquilo que o fascinou. Condição mental.', summary: '-2d20 em percepção, Sem ações' },
  { id: '20', name: 'Fatigado', description: 'O personagem fica fraco e vulnerável. Se o personagem ficar fatigado novamente, em vez disso fica exausto. Condição de fadiga.', summary: 'Fraco, Vulnerável', causes: ['21', '36'] },
  { id: '21', name: 'Fraco', description: 'O personagem sofre -2d20 em testes de Agilidade, Força e Vigor. Se ficar fraco novamente, em vez disso fica debilitado.', summary: '-2d20 em testes' },
  { id: '22', name: 'Frustrado', description: 'O personagem sofre -2d20 em testes de Intelecto e Presença. Se ficar frustrado novamente, em vez disso fica esmorecido. Condição mental.', summary: '-2d20 em testes' },
  { id: '23', name: 'Imóvel', description: 'Todas as formas de deslocamento do personagem são reduzidas a 0m. Condição de paralisia.', summary: 'Deslocamento 0m' },
  { id: '24', name: 'Inconsciente', description: 'O personagem fica indefeso e não pode fazer ações, incluindo reações. Condição mental.', summary: 'Indefeso, Sem ações', causes: ['25'] },
  { id: '25', name: 'Indefeso', description: 'O personagem é considerado desprevenido, mas sofre -10 na Defesa, falha automaticamente em testes de Reflexos e pode sofrer golpes de misericórdia.', summary: 'Desprevenido, -10 Defesa, Falha em reflexos', causes: ['11'] },
  { id: '26', name: 'Lento', description: 'Todas as formas de deslocamento do personagem são reduzidas à metade e ele não pode correr ou fazer investidas. Condição de paralisia.', summary: 'Metade Deslocamento' },
  { id: '27', name: 'Machucado', description: 'O personagem tem menos da metade de seus pontos de vida totais.', summary: 'Vida < 50%' },
  { id: '28', name: 'Morrendo', description: 'Com 0 PV. Fica inconsciente e, se terminar 3 rodadas morrendo, morre.', summary: 'Inconsciente, 3 rodadas para morte', causes: ['24'] },
  { id: '29', name: 'Ofuscado', description: 'O personagem sofre -2d20 em testes de ataque e de Percepção. Condição de sentidos.', summary: '-2d20 em ataque, -2d20 em percepção' },
  { id: '30', name: 'Paralisado', description: 'O personagem fica imóvel e indefeso e só pode realizar ações puramente mentais. Condição de paralisia.', summary: 'Imóvel, Indefeso, Ações mentais', causes: ['23', '25'] },
  { id: '31', name: 'Pasmo', description: 'O personagem não pode fazer ações. Condição mental.', summary: 'Sem ações' },
  { id: '32', name: 'Petrificado', description: 'O personagem fica inconsciente e recebe resistência a dano 10.', summary: 'Inconsciente, RD 10', causes: ['24'] },
  { id: '33', name: 'Sangrando', description: 'No início de seus turnos, deve fazer um teste de Vigor (DT 20). Se falhar, perde 1d6 PV.', summary: '1d6 Dano/turno' },
  { id: '34', name: 'Surdo', description: 'O personagem não pode fazer testes de Percepção para ouvir e sofre -2d20 em testes de Iniciativa. Condição de sentidos.', summary: '-2d20 em iniciativa, Sem ouvir' },
  { id: '35', name: 'Surpreendido', description: 'Não ciente de seus inimigos. O personagem fica desprevenido e não pode fazer ações.', summary: 'Desprevenido, Sem ações', causes: ['11'] },
  { id: '36', name: 'Vulnerável', description: 'O personagem sofre -5 na Defesa.', summary: '-5 Defesa' },
  { id: '37', name: 'Pânico', description: 'O personagem sofre -2d20 em testes de perícia e deve fugir da fonte do medo. Se não puder, fica pasmo. Condição de medo.', summary: '-2d20 em perícia, Fugir' },
  { id: '38', name: 'Desesperado', description: 'O personagem sofre -5d20 em testes de Intelecto e Presença. Se ficar desesperado novamente, fica inconsciente. Condição mental.', summary: '-5d20 em testes' },
];
